# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
  namespace: storage-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes
          image: gcr.io/google-samples/service-catalog/cloud-storage-user:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-account
              mountPath: /var/secrets/service-account
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/service-account/privateKeyData
            - name: STORAGE_PROJECT
              valueFrom:
                secretKeyRef:
                  name: user-storage-binding
                  key: projectId
            - name: STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: user-storage-binding
                  key: bucketId
          ports:
            - containerPort: 8080
      volumes:
        - name: service-account
          secret:
            secretName: user-storage-binding
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-service
  namespace: storage-quotes
  labels:
    app: quotes
spec:
  selector:
    app: quotes
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
# A binding for the quotes deployment
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: user-storage-binding
  namespace: storage-quotes
spec:
  instanceRef:
    name: storage-instance
  parameters:
    serviceAccount: storage-user
    createServiceAccount: true
    roles:
      - roles/storage.objectCreator
      - roles/storage.objectViewer
