# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: admin-spanner-binding
  namespace: spanner-guestbook
spec:
  instanceRef:
    # The name of the service instance to 'bind to'. The act of binding will
    # grant the service account specified below specific roles so that it
    # can access the Spanner service instance with desired privileges.
    name: guestbook-spanner-instance
  parameters:
    # The service account which should be granted the administrative privileges.
    serviceAccount: guestbook-admin
    # Create a service account dedicated to this binding.
    createServiceAccount: true
    # List of roles to be granted. Because the guestbook-admin requires
    # administrative level access, `roles/spanner.admin` role is granted.
    roles:
      - roles/spanner.admin
